### ISSUE TITLE
Sidebar sticks open after initial opening, issue was brought on after install of Waterfox 38

### ISSUE THREAD

**Issue by barely-normal** [Quicksaver/OmniSidebar#89] opened 2015-05-18 08:33 UTC
Let me be clear about this, the problem was not there in Waterfox 37. However, since install of WF38, the sidebar will open with the browser once it has been opened in the browser. If I want to stop this behavior, I go into about:config and go to -

extensions.omnisidebar.lastStateMain;{"command":"omnisidebar-viewAddonSidebar","closed":false}

by changing to true, the behavior stops, but returns the next time the sidebar is opened, making the state of this go back to   false

It is a small thing, but quite annoying, as it was not that way before. Again, the problem does not appear, no matter the number of starts of the browser, until such time as the sidebar is opened, then the condition returns to false, and until manually corrected stays  false.

In case it matters-  Windows 7 Ultimate x64, and I have not taken the time to remove all the other extensions I run to see if this is remedied, but since the ONLY thing changed which brought this behavior is the update of the browser, I think it is likely the interaction between these two things.

**Comment by brianvanderburg2** [comment] 2015-06-05 15:44
I can confirm this on Firefox 38.0.5 Linux 64 as well, running in a blank profile with only OmniSidebar installed.  Every time I open the profile, the sidebar also opens.

**Comment by Quicksaver** [comment] 2015-06-12 11:08
I just added a fix for this. Could you please try beta version 1.6b4 (https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b4) and confirm that the issue is gone?

**Comment by Quicksaver** [comment] 2015-06-12 14:34
Correction, please try v1.6b5 https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b5

**Closed** 2015-06-15 13:08 UTC
Labels: bug, important
