### ISSUE TITLE
Automatic sidebar not working as expected

### ISSUE THREAD

**Issue by Gitoffthelawn** [Quicksaver/OmniSidebar#130] opened 2016-08-13 21:09 UTC
Thank you for your great tools! :+1: 

I might be misunderstanding part of the purpose of this extension.  The description says "Bring your bookmarks into view with just a gesture".  I think that means that the user can just place the cursor on a window border to get the sidebar to appear.

The first time I try this, it works perfectly.  After that, it never works.

I tried creating a new profile, but same issue there.

Am I misunderstanding something, or is it not currently working as designed?

Tested using Firefox 48.0.0.

**Comment by Quicksaver** [comment] 2016-08-14 19:07
Are you closing the sidebar at any point? Remember that "closing" and "hiding" the sidebar are two very different things. When you "close" the sidebar, it functions pretty much as before, you'll have to explicitly open it again by clicking the bookmarks button or in any other way you're accustomed to.

When you set it to automatically "hide", the sidebar simply rolls off to the side when you move the cursor away from it. As long as you don't "close" it, then it should appear as intended when you move the cursor back in there.

**Comment by Quicksaver** [comment] 2016-08-14 19:07
Is this not happening?

**Comment by Gitoffthelawn** [comment] 2016-08-15 04:30
Great explanation.  Thanks.  I'll try it again and let you know.

**Comment by Quicksaver** [comment] 2016-11-24 13:40
Please let me know if you still have any issues and it's not what I mentioned above.

**Closed** 2016-11-24 13:40 UTC
Labels: question
