### ISSUE TITLE
OmniSidebar buttn on the Add-ons toolbar in firefox reqires two clicks

### ISSUE THREAD

**Issue by sendinf** [Quicksaver/OmniSidebar#86] opened 2015-04-05 19:56 UTC
To open the sidebar, sometimes I had to press the OmniSidebar button only once, and sometimes - twice. In my opinion, this is very annoying. The problem disappeared when I put a tick next to 'Keep the panel loaded when sidebar closes'. Please make the Sidebar to be opened only when the button is pressed just once, if it possible. 
Best regards,
SendInf.

**Comment by Xinok** [comment] 2015-04-11 02:49
I'm unable to reproduce this issue. Can you provide some details of what versions of OmniSidebar, Firefox, and which OS you are running?

OmniSidebar 1.5.4
Firefox 37.0.1
Windows 8.1 Ultimate x64

**Comment by sendinf** [comment] 2015-04-11 09:02
Thank you for the response. 
Sorry that I did not specify at once, such an effect occurs only when the Sidebar is undocked. When the Sidebar is docked, there is no such behavior is not observed. 
And it looks like that's not the point 'Keep the panel loaded when sidebar closes'. If you change many of the settings, the OmniSidebar button  will work fine for a while, but then it comes back. 

OmniSidebar 1.5.4
Firefox 37.0.1
Windows XP SP3 x86

**Comment by Quicksaver** [comment] 2015-04-22 15:21
I also can't reproduce this. Since this only happens when the sidebar is undocked for you, can you be sure the sidebar isn't only hidden to the side? Remember that "hidden" and "closed" are two different things, you might be just closing the sidebar when it's hidden to the side when you'd just need to move the mouse over to the margin to show it.

**Closed** 2015-06-12 11:12 UTC
Labels: bug, unconfirmed
